name: Probando los triggers
run-name: Prueba de triggers
on: 
  push:
    branches: 
      - 'aprendiendo-github-actions'
  pull_request:
    types:
      - [opened, closed]
    branches:
      - 'aprendiendo-github-actions'
  issues:
    types: [opened, edited, closed]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Probando hola mundo
        run: python hola-mundo.py
      - name: probando test
        run: python test.py